views.py
from crypt import methods
from flask import Blueprint, render_template, request, flash,  redirect , url_for, jsonify
from flask_login import login_user, login_required, current_user, logout_user


from models import User,List,Card
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
import uuid

db = SQLAlchemy()
views = Blueprint('views', __name__)

#<------------------------------------------Auth------------------------------------------------>

@views.route('/')
def home():
    return render_template('index.html')

@views.route('/about')
def about():
    return render_template('about.html')

@views.route('/login')
def login():
    return render_template('login.html')

@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))

@views.route('/summary')
def summary():
    lists = db.session.query(List).filter_by(creator_id=current_user.id).all()
    cards = db.session.query(Card).filter_by(creator_id=current_user.id).all()
    date=datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    lists=len(lists)
    tasks=len(cards)
    past_deadline=0
    list=[]
    data=[0,0,0,0,0,0,0,0,0,0,0,0]
    strdata=''
    completed=0
    for card in cards:
        if (card.deadline) and (date>card.deadline.strftime("%Y/%m/%d %H:%M:%S")) and (card.complete_flag==False):
            past_deadline=past_deadline+1
        if (card.completed_on) and (card.complete_flag==True):
            completed=completed+1
            list.append(card.completed_on.strftime("%B"))
    for month in list:
        if month=="January": data[1]=data[1]+1
        if month=="February": data[2]=data[2]+1
        if month=="March": data[3]=data[3]+1
        if month=="April": data[4]=data[4]+1
        if month=="May": data[5]=data[5]+1
        if month=="June": data[6]=data[6]+1
        if month=="July": data[7]=data[7]+1
        if month=="August": data[8]=data[8]+1
        if month=="September": data[9]=data[9]+1
        if month=="October": data[10]=data[10]+1
        if month=="November": data[11]=data[11]+1
        if month=="December": data[12]=data[12]+1
    for ele in data:
        strdata=strdata+','+str(ele)
    return render_template('summary.html', data=strdata[1:], past_deadline=past_deadline, completed=completed, lists=lists,tasks=tasks)

@views.route('/login', methods=["POST"])
def login_post():
    username = request.form.get('username')
    password = request.form.get('password')
    remember = True

    user=db.session.query(User).filter_by(username=username).first()
    if user==None:
        flash("User does not exist.")
        return redirect(url_for('views.login'))
    user=db.session.query(User).filter_by(username=username,password=password).first()
    if user:
        login_user(user, remember=remember)  
        return redirect(url_for('views.dashboard'))
    else:
        flash("Password not correct.")
        return redirect(url_for('views.login'))


@views.route('/register')
def register():
    return render_template('register.html')

@views.route('/register', methods=["POST"])
def register_post():
    username = request.form.get('username')
    password = request.form.get('password')
    if username == ""  or password == "":
        flash('Username or password cannot be empty. Please try again.')
        return redirect(url_for('views.register'))
    user=db.session.query(User).filter_by(username=username).first()
    if user:
        flash('User already exists.')
        return redirect(url_for('views.register'))

    new_user = User(
        id=str(uuid.uuid4()),
        username=username,
        password=password,
    )
    db.session.add(new_user)
    db.session.commit()
    
    user=db.session.query(User).filter_by(username=username,password=password).first()
    return render_template("dashboard.html")

#<------------------------------------------Lists------------------------------------------------>

@views.route('/dashboard')
@login_required
def dashboard(): #send lists and cards
    lists = db.session.query(List).filter_by(creator_id=current_user.id).all()
    cards = db.session.query(Card).filter_by(creator_id=current_user.id).all()
    date=datetime.now().strftime("%Y/%m/%d %H:%M:%S")

    if lists==[]:
        flash("Create a list to get started -->")
        return render_template("dashboard.html")
    return render_template("dashboard.html", lists=lists, cards=cards, date=date)
    
@views.route('/list')
@login_required
def list():
    return render_template('list.html')

@views.route('/list', methods=['POST'])
@login_required
def newlist(): #create list
    list_name=request.form.get('list_name')
    if list_name == "":
        flash("list name cannot be empty. Please try again.")
        return redirect(url_for('views.dashboard'))
    print(list_name)
    list = db.session.query(List).filter_by(list_name=list_name, creator_id=current_user.id).first()
    if list:
        flash("List already exists")
        return redirect(url_for('views.dashboard'))

    converted_date=datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    converted_date=datetime.strptime(converted_date, '%Y/%m/%d %H:%M:%S') 
    
    new_list = List(
        list_id=str(uuid.uuid4()),
        list_name=request.form.get('list_name'),
        creator_id=current_user.id,
        updated_on=converted_date,
    )
    db.session.add(new_list)
    db.session.commit()
    return redirect(url_for('views.dashboard'))

@views.route('/edit/list/<list_id>')
def edit_list_name(list_id):
    list = db.session.query(List).filter_by(list_id=list_id,creator_id=current_user.id).first()
    list_name=list.list_name
    return render_template('editlist.html',list_id=list_id,list_name= list_name)

@views.route('/list/<list_id>', methods=['POST'])
@login_required
def editlist(list_id): #edit list
    new_list_name=request.form.get('new_list_name')
    print(new_list_name)
    if new_list_name == "":
        flash("list name cannot be empty. Please try again.")
        return redirect(url_for('views.dashboard'))

    list = db.session.query(List).filter_by(list_name=new_list_name,creator_id=current_user.id).first()
    if list:
        flash("List already exists")
        return redirect(url_for('views.dashboard'))
    list=db.session.query(List).get(list_id)
    list.list_name=new_list_name
    db.session.commit()
    converted_date=datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    converted_date=datetime.strptime(converted_date, '%Y/%m/%d %H:%M:%S') 
    list.updated_on=converted_date    
    db.session.commit()
    return redirect(url_for('views.dashboard'))

@views.route('/delete/list/<list_id>')
@login_required
def dellist(list_id): # delete list
    cards = db.session.query(Card).filter_by(list_id=list_id).all()
    if cards!=[]:
        for card in cards:
            db.session.delete(card)
    list = db.session.query(List).filter_by(list_id=list_id).first()
    db.session.delete(list)
    db.session.commit()
    return redirect(url_for('views.dashboard'))

#<------------------------------------------Cards------------------------------------------------>



@views.route('/card/<card_id>')    
@login_required
def api_get_card(card_id): # get one card 
    card = db.session.query(Card).filter_by(card_id=card_id).first()
    if card:    
        return render_template("card.html", card=card)
    flash("No card found.")
    return redirect(url_for('views.list'))

@views.route('/newcard/<list_id>')
@login_required
def card(list_id):
    return render_template('card.html',list_id=list_id)

@views.route('/newcard/<list_id>', methods=['POST'])
@login_required   
def newcard(list_id): # create new card

    title = request.form.get('title')
    content = request.form.get('content')
    deadline = request.form.get('deadline')

    if title == "":
        flash("Title cannot be empty. Please try again.")
        return redirect(url_for('views.newcard'))

    
    if content==None:
        content=''
    card = db.session.query(Card).filter_by(title=title, content=content, list_id=list_id).first()
    if card:
        flash("Card already exists in list.")
        return redirect(url_for('views.new'))
    if deadline == "":
        deadline=None
    else:    
        deadline = deadline.replace("T", " ")
        deadline = deadline.replace("-", "/")
        deadline=deadline+":00"

        deadline= datetime.strptime(deadline, '%Y/%m/%d %H:%M:%S')
    converted_date=datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    converted_date=datetime.strptime(converted_date, '%Y/%m/%d %H:%M:%S') 
    new_card = Card(
        creator_id= current_user.id,
        card_id=str(uuid.uuid4()),
        list_id=list_id,
        title=title,
        content=content,
        deadline=deadline,
        created_on=converted_date
    )
    db.session.add(new_card)
    db.session.commit()

    list=db.session.query(List).get(list_id)
    converted_date=datetime.now().strftime("%Y/%m/%d %H:%M:%S")
    converted_date=datetime.strptime(converted_date, '%Y/%m/%d %H:%M:%S') 
    list.updated_on=converted_date
    db.session.commit()
    return redirect(url_for('views.dashboard'))

@views.route('/edit/card/<card_id>')
def edit_card_name(card_id):
    card = db.session.query(Card).filter_by(card_id=card_id,creator_id=current_user.id).first()
    title=card.title
    content=card.content
    deadline=card.deadline
    return render_template('editcard.html',card_id=card_id,title=title,content=content,deadline=deadline)

@views.route('/edit/card/<card_id>', methods=['POST'])
@login_required    
def editcard(card_id): #edit card
    card = db.session.query(Card).get(card_id)

    title = request.form.get('title')
    content = request.form.get('content')
    deadline = request.form.get('deadline')
    if deadline=='':
        deadline=None
    else:
        deadline = deadline.replace("T", " ")
        deadline = deadline.replace("-", "/")
        deadline=deadline+":00"
        deadline= datetime.strptime(deadline, '%Y/%m/%d %H:%M:%S')

templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/styles.css">
    <title>About Page</title>
</head>

<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('views.home') }}">Kanban App</a>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('views.home') }}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.register') }}">Register</a>
                </li>
            </ul>
        </div>
    </nav>

    <h1>About Page</h1>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It
        has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
    <h3> What is Lorem Ipsum?</h3>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It
        has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
        publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

    <h3>Why do we use it?</h3>
    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content
        here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.
        Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

</body>

</html>

templates/card.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="../static/css/styles.css">
    <title>Kanban App</title>
</head>

<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="container">

            <a class="navbar-brand" href="{{ url_for('views.home') }}">Kanban App</a>

            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.dashboard') }}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.summary') }}">Summary</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.logout') }}">Logout</a>
                </li>
            </ul>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top: 15vh;">
        <h1>{{list_name}}</h1>
        {% with messages = get_flashed_messages() %} {% if messages %}
        <div class="d-flex justify-content-center">
            <div class="alert alert-primary text-center" style="width: 900px;">
                {{ messages[-1] }}
            </div>
        </div>
        {% endif %} {% endwith %}
    </div>
    <div class="container" style="margin-top: 10vh;">
        <form action="/newcard/{{list_id}}" method="post">
            <div class="form-group form-outline form-white mb-4">
                <label class="form-label" for="title">Title</label>
                <input name="title" type="text" id="title" class="form-control form-control-lg" />
            </div>

            <div class="form-group form-outline form-white mb-4">
                <label class="form-label" for="content">Content</label>
                <input name="content" type="text" id="content" class="form-control form-control-lg" />
            </div>

            <div class="form-group form-outline form-white mb-4" style="width:20rem;">
                <label class="form-label" for="deadline">Deadline</label>
                <input name="deadline" type="datetime-local" id="deadline" class="form-control form-control-lg" />
            </div>

            <button type="submit" id="submitButton" class="btn btn-outline-dark btn-lg px-5">Add card</button>

        </form>
    </div>
</body>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.6.0/umd/popper.min.js" integrity="sha512-BmM0/BQlqh02wuK5Gz9yrbe7VyIVwOzD1o40yi1IsTjriX/NGF37NyXHfmFzIlMmoSIBXgqDiG1VNU6kB5dBbA==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="static/css/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <style>
        i {
            color: rgb(49, 49, 49);
        }
    </style>
    <title>Kanban App</title>
</head>

<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('views.home') }}">Kanban App</a>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.summary') }}">Summary</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.logout') }}">Logout</a>
                </li>
            </ul>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-11">
                <h1>Dashboard</h1>
            </div>
            <div class="col-1" id="createlist">
                <a href="/list">
                    <i class="bi bi-clipboard-plus-fill d-flex justify-content-end" style="font-size: 3rem;" data-toggle="tooltip" data-placement="top" title="Add List"></i>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-1"></div>
            {% with messages = get_flashed_messages() %} {% if messages %}
            <div class="col-9 d-flex justify-content-center">
                <div class="alert alert-primary text-center" style="width: 900px;">
                    {{ messages[-1] }}
                </div>
            </div>
            {% endif %} {% endwith %}
            <div class="col-2"></div>
        </div>

    </div>
    <div class="container mb-4">
        <div class="row">
            {% for list in lists %}
            <div class="col-lg-4 mt-4">
                <div class="card bg-dark text-white" style="border-radius: 2%">
                    <div class="row">
                        <div class="col-1"></div>
                        <div class="col-9">
                            <h4 class="card-title mt-3 text-center">{{list.list_name}}</h4>
                        </div>
                        <div class="col-1">
                            <div class="dropdown">
                                <button class="btn btn-dark btn-sm dropdown-toggle mt-3" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" href="edit/list/{{list['list_id']}}">Edit list name</a></li>
                                    <li><a class="dropdown-item" href="delete/list/{{list['list_id']}}">Delete list</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pt-0">

                        {% for card in cards %} {% if list.list_id == card.list_id%}
                        <div class="card mt-2 ">


                            <div class="card-body pb-2 pt-2">
                                <div class="row">
                                    <div class="col-9">
                                        {% if card.deadline and date>card.deadline.strftime("%Y/%m/%d %H:%M:%S") and card.complete_flag==False%} {% if card.content==''%}
                                        <h6 class="card-title my-2 text-danger">{{card.title}}</h6>
                                        {%else%}
                                        <h6 class="card-title text-danger">{{card.title}}</h6>
                                        {%endif%} {%else%} 
                                        
                                        {% if card.content==''%}
                                        <h6 class="card-title my-2 text-dark">{{card.title}}</h6>
                                        
                                        {%else%}
                                        <h6 class="card-title text-dark">{{card.title}}</h6>
                                        
                                        {%endif%} 
                                        
                                        
                                        {%endif%} {% if card.content!=''%}
                                        <h6 class="card-subtitle text-muted">{{card.content}}</h6>
                                        {%endif%} {% if card.deadline!=None%}
                                        <div class="row mt-1">
                                            <div class="col-1">
                                                <i class="bi bi-calendar-event-fill d-flex justify-content-start"></i>
                                            </div>
                                            <div class="col-9 mt-1">
                                                <h6 class="card-subtitle text-muted">{{card.deadline.strftime('%-I:%M %p (%-d %b %Y)')}}</h6>
                                            </div>
                                        </div>
                                        {%endif%}

                                    </div>
                                    <div class="col-1 pt-3">
                                        {% if card.complete_flag==True%}
                                        <i class="bi bi-check-circle d-flex justify-content-end" style="font-size: 20px;"></i> {% endif%}
                                    </div>
                                    <div class="col-2 pt-2">
                                        <div class="dropdown">
                                            <button class="btn btn-light btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                            </button>
                                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                                {% if card.complete_flag==True%}
                                                <li><a class="dropdown-item" href="/incompleted/card/{{card['card_id']}}">Mark as incompleted</a></li>
                                                {%else%}
                                                <li><a class="dropdown-item" href="/completed/card/{{card['card_id']}}">Mark as completed</a></li>
                                                {% endif%}
                                                <li><a class="dropdown-item" href="edit/card/{{card['card_id']}}">Edit card</a></li>
                                                <li><a class="dropdown-item" href="delete/card/{{card['card_id']}}">Delete card</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        {% endif %} {% endfor %}
                        <div class="mt-3 ">
                            <a href="/newcard/{{list['list_id']}} ">
                                <i style="color: antiquewhite;font-size: 1.5rem; " class="bi bi-plus-square-fill d-flex justify-content-center " data-toggle="tooltip " data-placement="top " title="Add card "></i>
                            </a>

                        </div>
                    </div>

                </div>

            </div>{% endfor %}
        </div>
    </div>

</body>

</html>

templates/editcard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Kanban App</title>
</head>

<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('views.home') }}">Kanban App</a>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.dashboard') }}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.summary') }}">Summary</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.logout') }}">Logout</a>
                </li>
            </ul>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top: 15vh;">
        <form action="/edit/card/{{card_id}}" method="post">
            <div class="form-group form-outline form-white mb-4">
                <label class="form-label" for="title">Title</label>
                <input name="title" type="text" id="title" value="{{title}}" class="form-control form-control-lg" />
            </div>

            <div class="form-group form-outline form-white mb-4">
                <label class="form-label" for="content">Content</label>
                <input name="content" type="text" id="content" value="{{content}}" class="form-control form-control-lg" />
            </div>

            <div class="form-group form-outline form-white mb-4" style="width:20rem;">
                <label class="form-label" for="deadline">Deadline</label>
                <input name="deadline" type="datetime-local" id="deadline" value="{{deadline}}" class="form-control form-control-lg" />
            </div>

            <button type="submit" id="submitButton" class="btn btn-outline-dark btn-lg px-5">Save Changes</button>

        </form>
    </div>
</body>

</html>

templates/editlist.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Kanban App</title>
</head>

<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('views.home') }}">Kanban App</a>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.dashboard') }}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.summary') }}">Summary</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.logout') }}">Logout</a>
                </li>
            </ul>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top: 15vh;">
        <form action="/list/{{list_id}}" method="post">
            <div class="form-group form-outline form-white mt-4">
                <label class="form-label" for="list_name">List Name</label>
                <input name="new_list_name" type="text" id="list_name" placeholder="{{list_name}}" class="form-control form-control-lg" />
            </div>

            <button type="submit" id="submitButton" class="btn btn-outline-dark btn-lg px-5">Save Changes</button>
        </form>
    </div>
</body>

</html>

templates/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Kanban App</title>
</head>

<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('views.home') }}">Kanban App</a>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.dashboard') }}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.summary') }}">Summary</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.logout') }}">Logout</a>
                </li>
            </ul>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top: 15vh;">
        <form action="/list" method="post">
            <div class="form-group form-outline form-white mb-4">
                <label class="form-label" for="list_name">List Name</label>
                <input name="list_name" type="list_name" id="list_name" class="form-control form-control-lg" />
            </div>

            <button type="submit" id="submitButton" class="btn btn-outline-dark btn-lg px-5">Add List</button>

    </div>
</body>

</html>